"""Shared pytest fixtures for the wallapop-to-vinted suite.

Most fixtures here support the Phase 4 Page Object tests, which load
captured Vinted HTML into a Playwright page via ``page.set_content``.
The HTML files live under ``tests/fixtures/vinted_html/`` and are
regenerated by ``scripts/capture_vinted_fixtures.py`` against a live
session whenever Vinted's DOM shifts.
"""

from __future__ import annotations

from pathlib import Path

import pytest

FIXTURES_DIR = Path(__file__).parent / "fixtures" / "vinted_html"


@pytest.fixture
def load_vinted_fixture(page):
    """Return a callable that loads ``<scope>.html`` into the Playwright page.

    Usage in a test::

        def test_something(load_vinted_fixture):
            page = load_vinted_fixture("new_item")
            assert page.locator("[data-testid='title-input']").is_visible()

    If the fixture file doesn't exist (yet), the test is skipped with a
    pointer to the capture script — that's the friendly fail mode for
    contributors who haven't run the capture against their own session.
    """

    def _load(scope: str):
        path = FIXTURES_DIR / f"{scope}.html"
        if not path.exists():
            pytest.skip(
                f"Missing fixture {path.relative_to(Path(__file__).parent.parent)}. "
                f"Capture it with: python scripts/capture_vinted_fixtures.py --scope {scope}"
            )
        # wait_until="domcontentloaded" — the default ("load") waits for every
        # external resource (scripts, images, fonts) referenced in the HTML.
        # The captured fixtures are full Vinted pages (~2MB) with dozens of
        # CDN URLs that won't resolve from the test host, so the default makes
        # ``set_content`` race with hanging requests and fail intermittently.
        # We only need the DOM parsed to assert anchor presence.
        page.set_content(path.read_text(encoding="utf-8"), wait_until="domcontentloaded")
        return page

    return _load
